<?php
/**
 * Created by PhpStorm.
 * User: LYi-Ho
 * Date: 2018-11-26
 * Time: 09:22:44
 */

namespace Common\Model;

use Library\Traits\Model;
use PhalApi\long;
use PhalApi\Model\NotORMModel as NotORM;

/**
 * 京东签到 数据层
 * Class JdSignItem
 * @package Common\Model
 * @author  LYi-Ho 2018-11-26 09:22:44
 */
class JdSign extends NotORM
{
    use Model;

    /**
     * 根据ID更新数据
     * @param long $id
     * @param array         $data
     * @return int|TRUE
     */
    public function update($id, $data)
    {
        if (isset($data['return_data'])) {
            $data['return_data'] = serialize($data['return_data']);
        }
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    /**
     * 根据查询条件更新数据
     * @param array $condition
     * @param array $data
     * @return boolean|int 执行成功返回影响条数，失败返回false
     */
    public function updateByWhere($where, $data, $id = null)
    {
        if (!is_array($where)) {//更新条件不是数组，不允许更新，防止造成全表的更新
            return false;
        }
        if (isset($data['return_data'])) {
            $data['return_data'] = serialize($data['return_data']);
        }
        $this->formatExtData($data);
        return $this->getORM($id)->where($where)->update($data);
    }

    protected function getTableName($id)
    {
        return 'jd_sign';
    }


}
