<?php   
return array (
  'modelAdmin' => '\\app\\model\\Admin',
  'modelBaiDuId' => '\\app\\model\\BaiDuId',
  'modelChat' => '\\app\\model\\Chat',
  'modelChatMessage' => '\\app\\model\\ChatMessage',
  'modelCommon' => '\\app\\model\\Common',
  'modelCron' => '\\app\\model\\Cron',
  'modelDelivery' => '\\app\\model\\Delivery',
  'modelFriend' => '\\app\\model\\Friend',
  'modelIp' => '\\app\\model\\Ip',
  'modelJdSign' => '\\app\\model\\JdSign',
  'modelJdSignItem' => '\\app\\model\\JdSignItem',
  'modelJdSignLog' => '\\app\\model\\JdSignLog',
  'modelJdUser' => '\\app\\model\\JdUser',
  'modelLogistics' => '\\app\\model\\Logistics',
  'modelLogisticsCompany' => '\\app\\model\\LogisticsCompany',
  'modelMessage' => '\\app\\model\\Message',
  'modelReply' => '\\app\\model\\Reply',
  'modelSetting' => '\\app\\model\\Setting',
  'modelSubject' => '\\app\\model\\Subject',
  'modelTieBa' => '\\app\\model\\TieBa',
  'modelTopic' => '\\app\\model\\Topic',
  'modelUser' => '\\app\\model\\User',
);