<?php   
return array (
  'modelBaiduId' => 
  array (
    'id' => 'bigint',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
  'modelFile' => 
  array (
    'id' => 'bigint',
    'name' => 'string',
    'path' => 'string',
    'origin_name' => 'string',
    'mime_type' => 'string',
    'extension' => 'string',
    'size' => 'string',
    'width' => 'string',
    'height' => 'string',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
  'modelFundFund' => 
  array (
    'id' => 'bigint',
    'code' => 'string',
    'name' => 'string',
    'pinyin_initial' => 'string',
    'type' => 'string',
    'unit_net_value' => 'decimal',
    'cumulative_net_value' => 'decimal',
    'net_value_time' => 'integer',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
  'modelFundFundNetValue' => 
  array (
    'id' => 'bigint',
    'fund_id' => 'bigint',
    'code' => 'string',
    'name' => 'string',
    'unit_net_value' => 'decimal',
    'cumulative_net_value' => 'decimal',
    'net_value_time' => 'integer',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
  'modelFundFundValuation' => 
  array (
    'id' => 'bigint',
    'fund_id' => 'bigint',
    'code' => 'string',
    'name' => 'string',
    'unit_net_value' => 'decimal',
    'estimated_net_value' => 'decimal',
    'estimated_growth' => 'decimal',
    'estimated_growth_rate' => 'decimal',
    'valuation_time' => 'integer',
    'valuation_source' => 'string',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
  'modelOption' => 
  array (
  ),
  'modelOptionItem' => 
  array (
  ),
  'modelUser' => 
  array (
    'id' => 'bigint',
    'user_name' => 'string',
    'nick_name' => 'string',
    'real_name' => 'string',
    'mobile' => 'string',
    'email' => 'string',
    'email_verified_at' => 'integer',
    'previous_avatar' => 'string',
    'avatar' => 'string',
    'sex' => 'boolean',
    'birthdate' => 'integer',
    'last_login_time' => 'integer',
    'status' => 'boolean',
    'frozen_time' => 'integer',
    'open_id' => 'string',
    'password' => 'string',
    'o_pwd' => 'text',
    'remember_token' => 'string',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
  'modelUserFund' => 
  array (
    'id' => 'bigint',
    'user_id' => 'bigint',
    'fund_id' => 'bigint',
    'code' => 'string',
    'name' => 'string',
    'cost' => 'decimal',
    'share' => 'decimal',
    'amount' => 'decimal',
    'created_at' => 'integer',
    'updated_at' => 'integer',
    'deleted_at' => 'integer',
  ),
);